
routes: #网关路由策略
  - id: path_route
    uri: lb://cloud-provider
    predicates:
      - Path=/config/**

  - id: baiud_route
    uri: http://cn.bing.com/?ensearch=1&FORM=BEHPTB
    predicates:
      - Path=/comfig