
server:
  port: 9092
spring:
  application:
    name: cloud-provider
  cloud:
    nacos:
      discovery:
        server-addr: 182.61.146.178:8848
        #指定服务分组
        group: TEST_GROUP
        #指定命名空间
        namespace: 5520087e-2477-4463-bf60-aa5762f1e0ed
management:
  endpoints:
    web:
      exposure:
        include: '*'
config:
  info: why is
logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN    #静止心跳检测日志打印