server:
  port: 9091
spring:
  application:
    name: cloud-provider
  cloud:
    nacos:
      discovery:
        server-addr: 182.61.146.178:8848
        #指定分组
        group: DEV_GROUP
        #指定命名空间
        namespace: 7a7bbf66-9d2f-4c2d-9586-6720d09ff155
management:
  endpoints:
    web:
      exposure:
        include: '*'
config:
  info: why
logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN    #静止心跳检测日志打印
