server:
  port: 8082
spring:
  application:
    name: cloud-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 182.61.146.178:8848
        group: DEV_GROUP
        namespace: 7a7bbf66-9d2f-4c2d-9586-6720d09ff155

management:
  endpoint:
    nacos-discovery:
      enabled: true

