server:
  port: 8082
spring:
  application:
    name: cloud-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 182.61.146.178:8848
        group: DEV_GROUP
        namespace: f170aba7-4087-441c-a8c0-8c2b46415bb0

management:
  endpoint:
    nacos-discovery:
      enabled: true

